
Saved 1 image to runs\detect\exp
Internal Server Error: /foodbot/callback
Traceback (most recent call last):
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\foodbot\views.py", line 254, in callback
    line_bot_api.reply_message(event.reply_token, messages)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\deprecated\classic.py", line 285, in wrapper_function
    return wrapped_(*args_, **kwargs_)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\linebot\api.py", line 123, in reply_message
    self._post(
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\linebot\api.py", line 2116, in _post
    self.__check_error(response)
  File "C:\Users\murra\OneDrive\文件\GitHub\django_bot20240518\venv\lib\site-packages\linebot\api.py", line 2152, in __check_error
    raise LineBotApiError(
linebot.exceptions.LineBotApiError: LineBotApiError: status_code=400, request_id=8ada7326-1133-48f5-84b1-d5792e867957, error_response={"details": [{"message": "Must be a valid H
TTPS URL", "property": "messages[0].originalContentUrl"}, {"message": "Must be a valid HTTPS URL", "property": "messages[0].previewImageUrl"}], "message": "The request body has 
2 error(s)"}, headers={'Server': 'legy', 'Content-Type': 'application/json', 'x-content-type-options': 'nosniff', 'x-frame-options': 'DENY', 'x-line-request-id': '8ada7326-1133-
48f5-84b1-d5792e867957', 'x-xss-protection': '1; mode=block', 'Content-Length': '222', 'Expires': 'Sat, 18 May 2024 14:35:17 GMT', 'Cache-Control': 'max-age=0, no-cache, no-store', 'Pragma': 'no-cache', 'Date': 'Sat, 18 May 2024 14:35:17 GMT', 'Connection': 'close'}
[18/May/2024 22:35:17] "POST /foodbot/callback HTTP/1.1" 500 111250
